series: GLM Math
title: Nested Transforms Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: In this demo we explore how to apply transformations to nested vertices.
language: C++
tags:
  - Math
extra_resources:
connections:
  - series: GLM Math
    title: Quaternions Tutorial

